In [110]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
from sklearn import linear_model


In [111]:
# import dataset

charging_df = pd.read_csv('charging_data.csv')
charging_df


Unnamed: 0                betreiber  art_der_ladeeinrichung  \
0               0                  GGEW AG   Normalladeeinrichtung   
1               1            Pfalzwerke AG  Schnellladeeinrichtung   
2               2      ENTEGA Energie GmbH   Normalladeeinrichtung   
3               3         Entega Plus GmbH   Normalladeeinrichtung   
4               4         Entega Plus GmbH   Normalladeeinrichtung   
...           ...                      ...                     ...   
36765       36765  Stadtwerke Leipzig GmbH   Normalladeeinrichtung   
36766       36766  Stadtwerke Leipzig GmbH   Normalladeeinrichtung   
36767       36767  Stadtwerke Leipzig GmbH   Normalladeeinrichtung   
36768       36768  Stadtwerke Leipzig GmbH   Normalladeeinrichtung   
36769       36769  Stadtwerke Leipzig GmbH   Normalladeeinrichtung   

       anzahl_ladepunkte  anschlussleistung       steckertypen1  \
0                      1                4.6  AC Steckdose Typ 2   
1                      2               75.0  AC Steckdose Typ 2   
2                      2               44.0  AC Steckdose Typ 2   
3                      2               22.0  AC Steckdose Typ 2   
4                      2               22.0  AC Steckdose Typ 2   
...                  ...                ...                 ...   
36765                  2               30.0  AC Steckdose Typ 2   
36766                  2               30.0  AC Steckdose Typ 2   
36767                  2               30.0  AC Steckdose Typ 2   
36768                  2               30.0  AC Steckdose Typ 2   
36769                  2               22.0   AC Kupplung Typ 2   

            steckertypen2 steckertypen3 steckertypen4  p1_kw  ...  p4_kw  \
0                     NaN           NaN           NaN    4.6  ...    NaN   
1       DC Kupplung Combo           NaN           NaN   22.0  ...    NaN   
2      AC Steckdose Typ 2           NaN           NaN   22.0  ...    NaN   
3      AC Steckdose Typ 2           NaN           NaN   22.0  ...    NaN   
4      AC Steckdose Typ 2           NaN           NaN   22.0  ...    NaN   
...                   ...           ...           ...    ...  ...    ...   
36765  AC Steckdose Typ 2           NaN           NaN   22.0  ...    NaN   
36766  AC Steckdose Typ 2           NaN           NaN   22.0  ...    NaN   
36767  AC Steckdose Typ 2           NaN           NaN   22.0  ...    NaN   
36768  AC Steckdose Typ 2           NaN           NaN   22.0  ...    NaN   
36769   AC Kupplung Typ 2           NaN           NaN   11.0  ...    NaN   

         kreis_kreisfreie_stadt      ort postleitzahl                 strasse  \
0          Landkreis Bergstraße   Lorsch        64653             Klosterstr.   
1          Landkreis Bergstraße   Lorsch        64653        Nibelungenstraße   
2          Landkreis Bergstraße    Fürth        64658         Krumbacher Str.   
3          Landkreis Bergstraße    Fürth        64658           Erbacher Str.   
4          Landkreis Bergstraße    Fürth        64658               Schulstr.   
...                         ...      ...          ...                     ...   
36765  Kreisfreie Stadt Leipzig  Leipzig         4277       Bornaische Straße   
36766  Kreisfreie Stadt Leipzig  Leipzig         4277          Scheffelstraße   
36767  Kreisfreie Stadt Leipzig  Leipzig         4277       Bornaische Straße   
36768  Kreisfreie Stadt Leipzig  Leipzig         4277  Richard Lehmann Straße   
36769  Kreisfreie Stadt Leipzig  Leipzig         4277       Eichendorffstraße   

       hausnummer                                    adresszusatz  \
0              23                                             NaN   
1         135-137                                             NaN   
2              39                                             NaN   
3             102                                               a   
4              12                                             NaN   
...           ...                                            

In [112]:
charging_df.rename(columns={'art_der_ladeeinrichung': 'type_of_charging_equipment'}, inplace=True)

In [113]:
columns_list = charging_df.columns.tolist()
print(columns_list)

['Unnamed: 0', 'betreiber', 'type_of_charging_equipment', 'anzahl_ladepunkte', 'anschlussleistung', 'steckertypen1', 'steckertypen2', 'steckertypen3', 'steckertypen4', 'p1_kw', 'p2_kw', 'p3_kw', 'p4_kw', 'kreis_kreisfreie_stadt', 'ort', 'postleitzahl', 'strasse', 'hausnummer', 'adresszusatz', 'inbetriebnahmedatum', 'breitengrad', 'laengengrad']


In [114]:
charging_df.rename(columns={'anzahl_ladepunkte': 'number_of_charging_points'}, inplace=True)

In [115]:
charging_df.rename(columns={'anschlussleistung': 'connected_load'}, inplace=True)

In [116]:
charging_df.rename(columns={'steckertypen1': 'plug_types_1'}, inplace=True)

In [117]:
new_column_names = {'steckertypen2': 'plug_types_2', 'steckertypen3': 'plug_types_3', 'steckertypen4': 'plug_types_4','kreis_kreisfreie_stadt': 'district_city', 'ort': 'city', 'postleitzahl': 'zip_code', 'strasse': 'street', 'hausnummer': 'house_number', 'adresszusatz':'secondary_address','inbetriebnahmedatum': 'date_of_commissioning', 'breitengrad': 'latitude', 'laengengrad':'longitude'}
charging_df.rename(columns=new_column_names, inplace=True)

In [118]:
column_names = charging_df.columns.tolist()
print(column_names)

['Unnamed: 0', 'betreiber', 'type_of_charging_equipment', 'number_of_charging_points', 'connected_load', 'plug_types_1', 'plug_types_2', 'plug_types_3', 'plug_types_4', 'p1_kw', 'p2_kw', 'p3_kw', 'p4_kw', 'district_city', 'city', 'zip_code', 'street', 'house_number', 'secondary_address', 'date_of_commissioning', 'latitude', 'longitude']


In [119]:
charging_df.rename(columns={'betreiber': 'operator'}, inplace=True)

In [120]:
column_names = charging_df.columns.tolist()
print(column_names)

['Unnamed: 0', 'operator', 'type_of_charging_equipment', 'number_of_charging_points', 'connected_load', 'plug_types_1', 'plug_types_2', 'plug_types_3', 'plug_types_4', 'p1_kw', 'p2_kw', 'p3_kw', 'p4_kw', 'district_city', 'city', 'zip_code', 'street', 'house_number', 'secondary_address', 'date_of_commissioning', 'latitude', 'longitude']


In [121]:
charging_df.head()

Unnamed: 0             operator type_of_charging_equipment  \
0           0              GGEW AG      Normalladeeinrichtung   
1           1        Pfalzwerke AG     Schnellladeeinrichtung   
2           2  ENTEGA Energie GmbH      Normalladeeinrichtung   
3           3     Entega Plus GmbH      Normalladeeinrichtung   
4           4     Entega Plus GmbH      Normalladeeinrichtung   

   number_of_charging_points  connected_load        plug_types_1  \
0                          1             4.6  AC Steckdose Typ 2   
1                          2            75.0  AC Steckdose Typ 2   
2                          2            44.0  AC Steckdose Typ 2   
3                          2            22.0  AC Steckdose Typ 2   
4                          2            22.0  AC Steckdose Typ 2   

         plug_types_2 plug_types_3 plug_types_4  p1_kw  ...  p4_kw  \
0                 NaN          NaN          NaN    4.6  ...    NaN   
1   DC Kupplung Combo          NaN          NaN   22.0  ...    NaN   
2  AC Steckdose Typ 2          NaN          NaN   22.0  ...    NaN   
3  AC Steckdose Typ 2          NaN          NaN   22.0  ...    NaN   
4  AC Steckdose Typ 2          NaN          NaN   22.0  ...    NaN   

          district_city    city zip_code            street  house_number  \
0  Landkreis Bergstraße  Lorsch    64653       Klosterstr.            23   
1  Landkreis Bergstraße  Lorsch    64653  Nibelungenstraße       135-137   
2  Landkreis Bergstraße   Fürth    64658   Krumbacher Str.            39   
3  Landkreis Bergstraße   Fürth    64658     Erbacher Str.           102   
4  Landkreis Bergstraße   Fürth    64658         Schulstr.            12   

  secondary_address date_of_commissioning   latitude longitude  
0               NaN            2017-01-02  49.653064  8.572109  
1               NaN            2021-04-27  49.652969  8.554764  
2               NaN            2017-11-21  49.658037  8.787881  
3                 a            2022-04-08  49.663670  8.796830  
4               NaN            2022-04-08  49.646360  8.781410  

[5 rows x 22 columns]

In [122]:
charging_df['Unnamed: 0'].unique() 
#this seems like an identifier column, which does not make sense to consider in the analysis but will not drop it now

array([    0,     1,     2, ..., 36767, 36768, 36769])

In [123]:
charging_df['operator'].unique().T

array(['GGEW AG', 'Pfalzwerke AG', 'ENTEGA Energie GmbH', ...,
       'Auto Müller & Sohn OHG', 'Autohaus Dresden Reick GmbH & Co.KG',
       'Ingenieurbüro'], dtype=object)

In [124]:
value_counts1 = charging_df['operator'].value_counts()
first_values = value_counts1.head(100)  # Adjust the number according to your preference
print(first_values)

operator
E.ON Drive GmbH                        2154
EnBW mobility+ AG und Co.KG            2006
EWE Go GmbH                             894
Mercedes-Benz AG                        825
Westenergie Metering GmbH               795
                                       ... 
Stadtwerke Waiblingen GmbH               52
Stadtwerke Göttingen eMobil              51
Städtische Werke AG                      51
HanseWerk Charging Station               50
EMobility Netzwerk Deutschland GmbH      48
Name: count, Length: 100, dtype: int64


In [125]:
#data frame containing all the operators that only have 1 charger
single_charing_point=charging_df[charging_df['operator'].map(charging_df['operator'].value_counts()) == 1]
single_charing_point['operator'].nunique()

2969

In [126]:
charging_df['type_of_charging_equipment'].unique() 

array(['Normalladeeinrichtung', 'Schnellladeeinrichtung'], dtype=object)

In [127]:
charging_df['type_of_charging_equipment'] = charging_df['type_of_charging_equipment'].replace({'Normalladeeinrichtung': 'Standard_charger', 'Schnellladeeinrichtung': 'Super_charger'})

In [128]:
charging_df['type_of_charging_equipment'].unique() 

array(['Standard_charger', 'Super_charger'], dtype=object)

In [129]:
charging_df['number_of_charging_points'].unique() 

array([1, 2, 4, 3])

In [130]:
charging_df['connected_load'].unique() 

array([   4.6 ,   75.  ,   44.  ,   22.  ,  150.  ,   98.  ,   93.  ,
         11.  ,   39.6 ,  250.  ,  300.  ,   50.  ,  350.  ,   33.  ,
        600.  ,   88.  ,   30.  ,   72.  ,  160.  ,  175.  ,  100.  ,
         66.  ,   43.  ,   26.4 ,   52.8 ,   39.65,   52.99,   42.  ,
          5.83,   35.  ,  400.  ,  360.  ,   34.5 ,  144.  ,   14.7 ,
          3.7 ,   13.2 ,  120.  ,   13.75,   16.  ,   77.  ,   60.  ,
        215.  ,  320.  ,   25.  ,  240.  ,  110.  ,   26.5 ,   32.  ,
         45.  ,   97.  ,    4.2 ,  165.  ,  200.  ,   20.  ,   25.2 ,
          5.5 ,  176.  ,   96.  ,  570.  ,  122.  ,   80.  ,   55.  ,
         40.  ,  155.  ,    8.  ,   73.  ,   62.5 ,  116.74,    3.6 ,
         39.  ,   70.  ,   26.  ,  156.  ,   82.  ,   24.  ,  125.  ,
         46.  ,  173.  , 1100.  ,   13.25,   78.  ,  210.  ,   85.  ,
         39.4 ,  115.  ,  180.  ,  225.  ,  800.  ,  315.  ,    7.2 ,
         51.4 ,   21.  ,  124.  ,    3.  ,   86.  ,   14.  ,  104.  ,
        132.  ,   73

In [131]:
charging_df['connected_load'].dtype

dtype('float64')

In [132]:
charging_df['plug_types_1'].unique() 

array(['AC Steckdose Typ 2', 'DC Kupplung Combo', 'AC Kupplung Typ 2',
       'AC Steckdose Typ 2, AC Kupplung Typ 2',
       'DC Kupplung Combo, DC CHAdeMO', 'AC Steckdose Typ 2, AC Schuko',
       'AC Steckdose Typ 2, DC Kupplung Combo, DC CHAdeMO',
       'AC Kupplung Typ 2, DC CHAdeMO',
       'AC Kupplung Typ 2, DC Kupplung Combo',
       'AC Kupplung Typ 2, AC Schuko',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, AC CEE 5 polig',
       'AC Steckdose Typ 2, DC Kupplung Combo',
       'AC Kupplung Typ 2, DC Kupplung Combo, DC CHAdeMO',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, AC Schuko',
       'AC Steckdose Typ 2, DC Kupplung Combo, AC Schuko',
       'AC Schuko, AC CEE 5 polig',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, DC Kupplung Combo',
       'DC Kupplung Combo, AC CEE 3 polig',
       'AC Steckdose Typ 2, AC Schuko, AC CEE 5 polig',
       'AC Steckdose Typ 2, DC CHAdeMO',
       'AC Steckdose Typ 2, AC Schuko, DC CHAdeMO',
       'AC Steckdose Typ 2, AC Kupplu

In [133]:
charging_df['plug_types_2'].unique() 

array([nan, 'DC Kupplung Combo', 'AC Steckdose Typ 2',
       'DC Kupplung Combo, DC CHAdeMO', 'AC Kupplung Typ 2',
       'AC Steckdose Typ 2, AC Schuko',
       'AC Steckdose Typ 2, AC Kupplung Typ 2',
       'AC Kupplung Typ 2, DC CHAdeMO',
       'AC Kupplung Typ 2, DC Kupplung Combo',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, AC CEE 5 polig',
       'AC Steckdose Typ 2, DC Kupplung Combo',
       'AC Kupplung Typ 2, DC Kupplung Combo, DC CHAdeMO', 'DC CHAdeMO',
       'AC CEE 5 polig',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, DC CHAdeMO', 'AC Schuko',
       'AC Schuko, AC CEE 5 polig',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, DC Kupplung Combo',
       'AC Steckdose Typ 2, DC Kupplung Combo, AC Schuko',
       'DC Kupplung Combo, AC CEE 5 polig',
       'AC Steckdose Typ 2, DC CHAdeMO', 'AC Kupplung Typ 2, AC Schuko',
       'AC Steckdose Typ 2, AC CEE 3 polig',
       'AC Steckdose Typ 2, AC CEE 5 polig',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, AC Schuko'

In [134]:
charging_df['plug_types_3'].unique() 

array([nan, 'AC Steckdose Typ 2', 'AC Steckdose Typ 2, AC Kupplung Typ 2',
       'AC Steckdose Typ 2, AC Schuko', 'AC Kupplung Typ 2, DC CHAdeMO',
       'AC Kupplung Typ 2', 'DC Kupplung Combo', 'AC Schuko',
       'DC Kupplung Combo, DC CHAdeMO',
       'AC Kupplung Typ 2, DC Kupplung Combo',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, DC CHAdeMO', 'DC CHAdeMO',
       'AC Steckdose Typ 2, DC Kupplung Combo',
       'AC Steckdose Typ 2, AC CEE 5 polig',
       'AC Kupplung Typ 2, AC Schuko',
       'AC Kupplung Typ 2, AC CEE 5 polig',
       'AC Steckdose Typ 2, AC CEE 3 polig',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, AC Schuko',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, DC Kupplung Combo, DC CHAdeMO',
       'AC Steckdose Typ 2, DC CHAdeMO'], dtype=object)

In [135]:
charging_df['plug_types_4'].unique() 

array([nan, 'AC Steckdose Typ 2', 'DC Kupplung Combo',
       'AC Steckdose Typ 2, AC Schuko', 'AC Kupplung Typ 2',
       'AC Steckdose Typ 2, AC Kupplung Typ 2', 'AC Schuko',
       'AC Steckdose Typ 2, AC Kupplung Typ 2, AC Schuko, AC CEE 3 polig',
       'DC Kupplung Combo, DC CHAdeMO',
       'DC Kupplung Combo, DC CHAdeMO, Tesla',
       'AC Steckdose Typ 2, AC CEE 5 polig',
       'DC Kupplung Combo, Typ 2 / Tesla',
       'AC Kupplung Typ 2, AC CEE 5 polig', 'DC Kupplung Combo, Tesla',
       'AC Steckdose Typ 2, DC Kupplung Combo'], dtype=object)

In [136]:
#there seems to be some chargers which have up to 4 plug types 
charging_df['plug_types_4'].value_counts() 

plug_types_4
AC Steckdose Typ 2                                                  847
AC Kupplung Typ 2                                                   125
DC Kupplung Combo                                                    47
AC Schuko                                                            46
AC Steckdose Typ 2, AC Kupplung Typ 2                                30
AC Steckdose Typ 2, AC Schuko                                        22
DC Kupplung Combo, DC CHAdeMO                                         7
AC Steckdose Typ 2, DC Kupplung Combo                                 2
AC Steckdose Typ 2, AC Kupplung Typ 2, AC Schuko, AC CEE 3 polig      1
DC Kupplung Combo, DC CHAdeMO, Tesla                                  1
AC Steckdose Typ 2, AC CEE 5 polig                                    1
DC Kupplung Combo, Typ 2 / Tesla                                      1
AC Kupplung Typ 2, AC CEE 5 polig                                     1
DC Kupplung Combo, Tesla                           

In [137]:
charging_df['p1_kw'].unique() 

array([  4.6 ,  22.  , 150.  ,  43.  ,  11.  ,  50.  , 300.  , 350.  ,
       225.  , 175.  , 100.  ,   5.83,  17.  ,   3.7 ,  90.  ,  60.  ,
        13.75, 160.  ,  42.  ,  16.  ,  25.  , 120.  ,  75.  ,  39.  ,
         4.2 ,  80.  , 250.  ,   2.  ,  20.  , 200.  ,   5.5 , 320.  ,
       280.  , 180.  ,  40.  , 360.  ,   8.  ,  15.  ,  62.5 ,   3.6 ,
       125.  ,  24.  ,  78.  ,  65.  ,  45.  ,   7.2 ,  21.  , 156.  ,
       124.  ,   3.  ,  86.  ,   4.  ,   7.  ,  44.  ,   3.5 , 140.  ,
        30.  ,   9.  ,  98.  ,   3.8 ,  22.1 ,  70.  ,  35.  , 240.  ,
       184.  ,  22.2 , 134.  ,  53.  , 130.  , 110.  ,   7.4 ,   7.3 ,
       146.  ,  10.  ,   4.7 ,  19.  , 290.  ,   8.3 ,   6.4 ,   7.5 ,
         2.3 ,   5.  ,  16.5 ,   6.  ,  72.  ,  99.  ,   7.1 ,   1.  ,
       218.  ,  55.  , 185.  ,  49.  ,  21.75,  18.  , 256.  ,  48.  ,
       145.  ,  33.  ,  21.9 ,  12.  , 230.  ,  93.  ,  13.8 , 144.  ,
        11.4 ,  14.  ,   6.6 ,   7.36, 270.  , 149.  ,  62.  , 135.  ,
      

In [138]:
charging_df['p1_kw'].dtype

dtype('float64')

In [139]:
charging_df['p2_kw'].unique() 

array([   nan,  50.  ,  22.  , 150.  ,  11.  ,  42.  , 300.  , 225.  ,
        30.  ,  43.  ,  20.  , 350.  ,  17.  ,   3.7 ,  90.  ,  60.  ,
        13.75, 160.  , 100.  ,  25.  , 120.  ,  75.  ,  39.  , 320.  ,
       250.  , 200.  ,   5.5 , 280.  , 180.  ,  40.  , 360.  ,   8.  ,
        15.  ,   2.3 ,  24.  ,  32.  , 125.  ,  78.  ,  44.  ,  62.5 ,
       175.  , 156.  , 124.  ,  86.  ,   4.  ,   7.  ,   7.2 , 140.  ,
       240.  ,  70.  ,  16.  ,   4.6 ,  22.2 ,  22.1 , 134.  , 130.  ,
       110.  ,   3.  , 146.  ,  10.  ,  62.  ,  80.  ,  59.  ,  19.  ,
        21.  , 290.  ,  45.  ,  35.  ,   3.5 ,   5.  ,   7.5 ,  16.5 ,
        99.  ,   7.4 ,  55.  , 218.  ,  38.  ,  76.5 , 185.  ,   3.6 ,
        47.  ,  21.75,  18.  , 256.  , 145.  ,  36.  ,  23.  ,  33.  ,
        12.  , 230.  ,  49.  ,  93.  ,  11.4 ,   2.5 ,  14.  ,   2.  ,
         7.36, 270.  , 149.  , 155.  ,  17.25,   4.14, 135.  ])

In [140]:
charging_df['p3_kw'].unique() 

array([   nan,  11.  ,  22.  ,  44.  ,   7.5 ,  50.  ,   3.7 , 300.  ,
        60.  ,  43.  , 150.  ,   3.  , 225.  ,   3.6 ,  75.  , 175.  ,
       100.  ,   7.2 ,   2.  ,  30.  ,  25.  , 360.  ,  22.1 , 112.5 ,
       120.  , 350.  , 320.  , 160.  ,  20.  ,   5.  ,   2.3 , 180.  ,
         7.  ,  76.5 ,  10.  ,  18.  ,  36.  ,  23.  , 200.  ,  93.  ,
         3.5 ,  26.6 ,   7.36,  16.  ,  45.  ])

In [141]:
charging_df['p4_kw'].unique() 

array([  nan,  11. ,  22. , 100. ,  50. ,   3.7, 300. ,   3. , 150. ,
       225. ,  75. , 175. ,   3.6, 360. ,  43. ,  22.1,  37.5,  30. ,
       350. , 320. ,   2.3,   7. ,   7.5,  44. ,  18. ,   7.2, 180. ,
         7.4,   3.5,  16. ,  20. ])

In [142]:
charging_df['district_city'].unique() 

array(['Landkreis Bergstraße', 'Landkreis Darmstadt-Dieburg',
       'Landkreis Fulda', 'Landkreis Gießen', 'Landkreis Groß-Gerau',
       'Landkreis Hersfeld-Rotenburg', 'Landkreis Hochtaunuskreis',
       'Landkreis Kassel', 'Landkreis Lahn-Dill-Kreis',
       'Landkreis Limburg-Weilburg', 'Landkreis Main-Kinzig-Kreis',
       'Landkreis Main-Taunus-Kreis', 'Landkreis Marburg-Biedenkopf',
       'Landkreis Odenwaldkreis', 'Landkreis Offenbach',
       'Landkreis Rheingau-Taunus-Kreis', 'Landkreis Schwalm-Eder-Kreis',
       'Landkreis Vogelsbergkreis', 'Landkreis Waldeck-Frankenberg',
       'Landkreis Werra-Meißner-Kreis', 'Landkreis Wetteraukreis',
       'Kreisfreie Stadt Rostock', 'Kreisfreie Stadt Schwerin',
       'Landkreis Ludwigslust-Parchim',
       'Landkreis Mecklenburgische Seenplatte',
       'Landkreis Nordwestmecklenburg', 'Landkreis Rostock',
       'Landkreis Vorpommern-Greifswald', 'Landkreis Vorpommern-Rügen',
       'Kreisfreie Stadt Braunschweig', 'Kreisfreie St

In [143]:
charging_df['district_city'].value_counts()

district_city
Kreisfreie Stadt München              1410
Kreisfreie Stadt Berlin               1266
Kreisfreie Stadt Hamburg               943
Stadtkreis Stuttgart                   698
Landkreis Region Hannover              693
                                      ... 
Landkreis Birkenfeld                    13
Kreisfreie Stadt Pirmasens              13
Kreisfreie Stadt Amberg                 12
Kreisfreie Stadt Offenbach am Main       9
Kreisfreie Stadt Schwabach               9
Name: count, Length: 400, dtype: int64

'city', 'zip_code', 'street', 'house_number', 'secondary_address', 'date_of_commissioning', 'latitude', 'longitude'

In [144]:
charging_df['city'].unique() 

array(['Lorsch', 'Fürth', 'Zwingenberg', ..., 'Chemnitz-Röhrsdorf',
       'Dresden-Prohlis', 'Leipzig - Alt-West'], dtype=object)

In [145]:
value_counts2 = charging_df['city'].value_counts()
first_values1 = value_counts2.head(10)  # Adjust the number according to your preference
print(first_values1)

city
München                1403
Berlin                 1250
Hamburg                 938
Stuttgart               696
Hannover                474
Dortmund                451
Rüsselsheim am Main     411
Düsseldorf              401
Sindelfingen            329
Regensburg              310
Name: count, dtype: int64


In [146]:
value_counts2 

city
München                                   1403
Berlin                                    1250
Hamburg                                    938
Stuttgart                                  696
Hannover                                   474
                                          ... 
Oberelchingen                                1
Unterelchingen                               1
Buch                                         1
Röthenbach an der Pegnitz (Haimendorf)       1
Leipzig - Alt-West                           1
Name: count, Length: 5960, dtype: int64

In [147]:
cars_df = pd.read_csv('car_data.csv')
cars_df
#https://www.eea.europa.eu/en/topics/in-depth/electric-vehicles?activeAccordion=0c1d4a46-bfa0-4770-9a74-740c6919e894

/var/folders/pf/nfj1603d1fjc2xkhkrlls95m0000gn/T/ipykernel_16751/4214540322.py:1: DtypeWarning: Columns (2,3,8,12,28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  cars_df = pd.read_csv('car_data.csv')


ID Country                       VFN          Mp         Mh  \
0        77798939      FR  IP-DGY____EAT82552-VR3-0  STELLANTIS        PSA   
1        77798940      FR  IP-DGY____EAT82552-VR3-0  STELLANTIS        PSA   
2        77798941      FR  IP-DGY____EAT82552-VR3-0  STELLANTIS        PSA   
3        77798942      FR  IP-DGY____EAT82552-VR3-0  STELLANTIS        PSA   
4        77798943      FR  IP-DGY____EAT82552-VR3-0  STELLANTIS        PSA   
...           ...     ...                       ...         ...        ...   
9479275  85804985      DK                       NaN         NaN  DUPLICATE   
9479276  85804990      DK                       NaN         NaN  DUPLICATE   
9479277  85805000      DK                       NaN         NaN  DUPLICATE   
9479278  85805005      DK                       NaN         NaN  DUPLICATE   
9479279  85815141      DK                       NaN         NaN  DUPLICATE   

                                 Man  MMS                   Tan    T    Va  \
0                 PSA AUTOMOBILES SA  NaN  e9*2018/858*11066*03    N     D   
1                 PSA AUTOMOBILES SA  NaN  e9*2018/858*11066*03    N     D   
2                 PSA AUTOMOBILES SA  NaN  e9*2018/858*11066*03    N     D   
3                 PSA AUTOMOBILES SA  NaN  e9*2018/858*11066*03    N     D   
4                 PSA AUTOMOBILES SA  NaN  e9*2018/858*11066*03    N     D   
...                              ...  ...                   ...  ...   ...   
9479275          AUTOMOBILES PEUGEOT  NaN    e2*2007/46*0534*22    M     R   
9479276          AUTOMOBILES PEUGEOT  NaN    e2*2007/46*0534*22    M     R   
9479277          AUTOMOBILES PEUGEOT  NaN    e2*2007/46*0534*22    M     R   
9479278          AUTOMOBILES PEUGEOT  NaN    e2*2007/46*0534*22    M     R   
9479279  BAYERISCHE MOTOREN WERKE AG  NaN    e1*2007/46*1750*13  G5K  11AJ   

         ...         IT Ernedc (g/km) Erwltp (g/km)  De  Vf  Status  year  \
0        ...        NaN           NaN           NaN NaN NaN       P  2022   
1        ...        NaN           NaN           NaN NaN NaN       P  2022   
2        ...        NaN           NaN           NaN NaN NaN       P  2022   
3        ...        NaN           NaN           NaN NaN NaN       P  2022   
4        ...        NaN           NaN           NaN NaN NaN       P  2022   
...      ...        ...           ...           ...  ..  ..     ...   ...   
9479275  ...   e2 28 29           NaN           2.1 NaN NaN       P  2022   
9479276  ...   e2 28 29           NaN           2.1 NaN NaN       P  2022   
9479277  ...   e2 28 29           NaN           2.1 NaN NaN       P  2022   
9479278  ...   e2 28 29           NaN           2.1 NaN NaN       P  2022   
9479279  ...  e24 32 37           NaN           1.8 NaN NaN       P  2022   

         Date of registration  Fuel consumption   Electric range (km)  
0                  2022-12-30                1.3                 59.0  
1                  2022-10-27                1.3                 60.0  
2                  2022-10-31                1.3                 59.0  
3                  2022-11-30                1.3                 59.0  
4                  2022-10-27                1.3                 60.0  
...                       ...                ...                  ...  
9479275                   NaN                NaN                  NaN  
9479276                   NaN                NaN                  NaN  
9479277                   NaN                NaN                  NaN  
9479278                   NaN                NaN                  NaN  
9479279                   NaN                NaN                  NaN  

[9479280 rows x 38 columns]

In [148]:
cars_df['Country'].unique() 

array(['FR', 'NO', 'LV', 'ES', 'BE', 'PL', 'DE', 'SI', 'NL', 'HU', 'RO',
       'SE', 'IT', 'SK', 'AT', 'BG', 'GR', 'LU', 'PT', 'IS', 'MT', 'CY',
       'DK', 'HR', 'CZ', 'FI', 'IE', 'LT', 'EE'], dtype=object)

In [149]:
cars_df['Country'].value_counts()

Country
DE    2570994
FR    1638878
IT    1312627
ES     851105
PL     416075
BE     366557
NL     305887
SE     283679
AT     214394
CZ     185836
NO     174106
PT     156051
DK     143747
RO     129072
HU     111025
IE     105499
GR     105231
FI      79440
SK      78404
SI      45411
HR      42861
LU      38480
BG      28244
LT      24932
EE      20251
IS      16528
LV      16327
CY      11443
MT       6196
Name: count, dtype: int64

In [150]:
column_names_cars = cars_df.columns.tolist()
print(column_names_cars)

['ID', 'Country', 'VFN', 'Mp', 'Mh', 'Man', 'MMS', 'Tan', 'T', 'Va', 'Ve', 'Mk', 'Cn', 'Ct', 'Cr', 'r', 'm (kg)', 'Mt', 'Enedc (g/km)', 'Ewltp (g/km)', 'W (mm)', 'At1 (mm)', 'At2 (mm)', 'Ft', 'Fm', 'ec (cm3)', 'ep (KW)', 'z (Wh/km)', 'IT', 'Ernedc (g/km)', 'Erwltp (g/km)', 'De', 'Vf', 'Status', 'year', 'Date of registration', 'Fuel consumption ', 'Electric range (km)']


In [151]:
#create a data frame that is only considering Germany
cars_de_df = cars_df[cars_df['Country'] == 'DE']

In [152]:
cars_de_df

ID Country                       VFN          Mp         Mh  \
579410   80049550      DE  IP-MQB27SZ_A0_0549-TMB-1  VOLKSWAGEN      SKODA   
579411   80049554      DE  IP-MQB27SZ_A0_0549-TMB-1  VOLKSWAGEN      SKODA   
579412   80049559      DE  IP-MQB27SZ_A0_0539-TMB-1  VOLKSWAGEN      SKODA   
579413   80049562      DE  IP-MQB27SZ_A0_0549-TMB-1  VOLKSWAGEN      SKODA   
579414   80049563      DE  IP-MQB27SZ_A0_0539-TMB-1  VOLKSWAGEN      SKODA   
...           ...     ...                       ...         ...        ...   
9479257  79719120      DE             IP-0104-JT1-1         NaN  DUPLICATE   
9479258  79898480      DE          IP-0500779-NLH-1         NaN  DUPLICATE   
9479259  79898481      DE          IP-0500779-NLH-1         NaN  DUPLICATE   
9479260  79978520      DE           IP-050629-TMA-1         NaN  DUPLICATE   
9479261  79987802      DE          IP-0500707-TMA-1         NaN  DUPLICATE   

                                                 Man  MMS  \
579410                                 SKODA AUTO AS  NaN   
579411                                 SKODA AUTO AS  NaN   
579412                                 SKODA AUTO AS  NaN   
579413                                 SKODA AUTO AS  NaN   
579414                                 SKODA AUTO AS  NaN   
...                                              ...  ...   
9479257                    TOYOTA MOTOR EUROPE NV SA  NaN   
9479258  HYUNDAI ASSAN OTOMOTIV SANAYI VE TICARET AS  NaN   
9479259  HYUNDAI ASSAN OTOMOTIV SANAYI VE TICARET AS  NaN   
9479260        HYUNDAI MOTOR MANUFACTURING CZECH SRO  NaN   
9479261        HYUNDAI MOTOR MANUFACTURING CZECH SRO  NaN   

                          Tan          T         Va  ...        IT  \
579410     e8*2007/46*0349*14         NW  ABCDLAAX0  ...       NaN   
579411     e8*2007/46*0349*14         NW  ABCDLAAX0  ...       NaN   
579412     e8*2007/46*0349*14         NW  ABCDLAAX0  ...       NaN   
579413     e8*2007/46*0349*14         NW  ABCDLAAX0  ...       NaN   
579414     e8*2007/46*0349*14         NW  ABCDLAAX0  ...       NaN   
...                       ...        ...        ...  ...       ...   
9479257    e6*2007/46*0289*04  XA5(EU.M)  AXAL52(N)  ...       NaN   
9479258    e5*2007/46*0121*03        BC3      C5P51  ...  e5 29 37   
9479259    e5*2007/46*0121*03        BC3      C5P51  ...  e5 29 37   
9479260    e5*2007/46*1075*10        PDE      BBP91  ...       NaN   
9479261  e5*2018/858*00001*04       NX4E      F5P21  ...       NaN   

        Ernedc (g/km) Erwltp (g/km)  De  Vf  Status  year  \
579410            NaN           NaN NaN NaN       P  2022   
579411            NaN           NaN NaN NaN       P  2022   
579412            NaN           NaN NaN NaN       P  2022   
579413            NaN           NaN NaN NaN       P  2022   
579414            NaN           NaN NaN NaN       P  2022   
...               ...           ...  ..  ..     ...   ...   
9479257           NaN           NaN NaN NaN       P  2022   
9479258           NaN          2.17 NaN NaN       P  2022   
9479259           NaN          2.17 NaN NaN       P  2022   
9479260           NaN           NaN NaN NaN       P  2022   
9479261           NaN           NaN NaN NaN       P  2022   

         Date of registration  Fuel consumption   Electric range (km)  
579410             2022-10-17                5.9                  NaN  
579411             2022-05-24                5.9                  NaN  
579412             2022-04-29                5.4                  NaN  
579413             2022-05-11                5.9                  NaN  
579414             2022-05-10                5.4                  NaN  
...                       ...                ...                  ...  
9479257            2022-08-11                NaN                  NaN  
9479258            2022-08-29                NaN                  NaN  
9479259            2022-08-29                NaN                  NaN  
9479260            2022-04-05                NaN   

In [153]:
cars_de_df['Enedc (g/km)'].unique() 

array([nan,  0., 26., 31.])

In [154]:
cars_de= cars_de_df.drop(['Enedc (g/km)', 'Ewltp (g/km)', 'W (mm)', 'At1 (mm)', 'At2 (mm)', 'Ft', 'Fm', 'ec (cm3)', 'ep (KW)', 'z (Wh/km)', 'IT', 'Ernedc (g/km)', 'Erwltp (g/km)'], axis=1)
cars_de

ID Country                       VFN          Mp         Mh  \
579410   80049550      DE  IP-MQB27SZ_A0_0549-TMB-1  VOLKSWAGEN      SKODA   
579411   80049554      DE  IP-MQB27SZ_A0_0549-TMB-1  VOLKSWAGEN      SKODA   
579412   80049559      DE  IP-MQB27SZ_A0_0539-TMB-1  VOLKSWAGEN      SKODA   
579413   80049562      DE  IP-MQB27SZ_A0_0549-TMB-1  VOLKSWAGEN      SKODA   
579414   80049563      DE  IP-MQB27SZ_A0_0539-TMB-1  VOLKSWAGEN      SKODA   
...           ...     ...                       ...         ...        ...   
9479257  79719120      DE             IP-0104-JT1-1         NaN  DUPLICATE   
9479258  79898480      DE          IP-0500779-NLH-1         NaN  DUPLICATE   
9479259  79898481      DE          IP-0500779-NLH-1         NaN  DUPLICATE   
9479260  79978520      DE           IP-050629-TMA-1         NaN  DUPLICATE   
9479261  79987802      DE          IP-0500707-TMA-1         NaN  DUPLICATE   

                                                 Man  MMS  \
579410                                 SKODA AUTO AS  NaN   
579411                                 SKODA AUTO AS  NaN   
579412                                 SKODA AUTO AS  NaN   
579413                                 SKODA AUTO AS  NaN   
579414                                 SKODA AUTO AS  NaN   
...                                              ...  ...   
9479257                    TOYOTA MOTOR EUROPE NV SA  NaN   
9479258  HYUNDAI ASSAN OTOMOTIV SANAYI VE TICARET AS  NaN   
9479259  HYUNDAI ASSAN OTOMOTIV SANAYI VE TICARET AS  NaN   
9479260        HYUNDAI MOTOR MANUFACTURING CZECH SRO  NaN   
9479261        HYUNDAI MOTOR MANUFACTURING CZECH SRO  NaN   

                          Tan          T         Va  ...  r  m (kg)      Mt  \
579410     e8*2007/46*0349*14         NW  ABCDLAAX0  ...  1  1262.0  1398.0   
579411     e8*2007/46*0349*14         NW  ABCDLAAX0  ...  1  1277.0  1393.0   
579412     e8*2007/46*0349*14         NW  ABCDLAAX0  ...  1  1242.0  1361.0   
579413     e8*2007/46*0349*14         NW  ABCDLAAX0  ...  1  1262.0  1404.0   
579414     e8*2007/46*0349*14         NW  ABCDLAAX0  ...  1  1242.0  1378.0   
...                       ...        ...        ...  ... ..     ...     ...   
9479257    e6*2007/46*0289*04  XA5(EU.M)  AXAL52(N)  ...  1  1665.0  1780.0   
9479258    e5*2007/46*0121*03        BC3      C5P51  ...  1  1195.0  1320.0   
9479259    e5*2007/46*0121*03        BC3      C5P51  ...  1  1195.0  1320.0   
9479260    e5*2007/46*1075*10        PDE      BBP91  ...  1  1444.0  1522.0   
9479261  e5*2018/858*00001*04       NX4E      F5P21  ...  1  1566.0  1625.0   

         De  Vf  Status  year  Date of registration  Fuel consumption   \
579410  NaN NaN       P  2022            2022-10-17                5.9   
579411  NaN NaN       P  2022            2022-05-24                5.9   
579412  NaN NaN       P  2022            2022-04-29                5.4   
579413  NaN NaN       P  2022            2022-05-11                5.9   
579414  NaN NaN       P  2022            2022-05-10                5.4   
...      ..  ..     ...   ...                   ...                ...   
9479257 NaN NaN       P  2022            2022-08-11                NaN   
9479258 NaN NaN       P  2022            2022-08-29                NaN   
9479259 NaN NaN       P  2022            2022-08-29                NaN   
9479260 NaN NaN       P  2022            2022-04-05                NaN   
9479261 NaN NaN       P  2022            2022-07-26                NaN   

         Electric range (km)  
579410                   NaN  
579411                   NaN  
579412                   NaN  
579413                   NaN  
579414                   NaN  
...                      ...  
9479257                  NaN  
9479258                  NaN  
9479259                  NaN  
9479260                  NaN  
9479261                  NaN  

[2570994 rows x 25 columns]

In [155]:
cars_de.shape

(2570994, 25)

In [156]:
columns_cars = cars_de.columns.tolist()
print(columns_cars)

['ID', 'Country', 'VFN', 'Mp', 'Mh', 'Man', 'MMS', 'Tan', 'T', 'Va', 'Ve', 'Mk', 'Cn', 'Ct', 'Cr', 'r', 'm (kg)', 'Mt', 'De', 'Vf', 'Status', 'year', 'Date of registration', 'Fuel consumption ', 'Electric range (km)']


In [157]:
cars_de['Mp'].unique() 
#can drop this

array(['VOLKSWAGEN', 'TESLA-HONDA-JLR', nan, 'RENAULT-NISSAN-MITSUBISHI',
       'HYUNDAI MOTOR EUROPE', 'KIA', 'MAZDA-SUBARU-SUZUKI-TOYOTA', 'BMW',
       'STELLANTIS', 'FORD', 'MERCEDES-BENZ'], dtype=object)

In [158]:
cars_de['VFN'].unique() 
#can drop this

array(['IP-MQB27SZ_A0_0549-TMB-1', 'IP-MQB27SZ_A0_0539-TMB-1',
       'IP-MQB27SZ_B0_0539-TMB-1', ..., 'IP-MQB37AS_B0_0821-TMB-1',
       'IP-MQB37AS_A0_0821-TMB-1', 'IP-MQB37SZ_B1_0552-VSS-1'],
      dtype=object)

In [159]:
cars_de['Mh'].unique() 

array(['SKODA', 'TESLA', 'SAIC MOTOR CORPORATION', 'AA-IVA', 'HENAN SUDA',
       'DFSK', 'JIANGLING MOTOR', 'VOLVO', 'LANZHOU',
       'MITSUBISHI MOTORS THAILAND', 'HYUNDAI ASSAN', 'BENTLEY',
       'NISSAN AUTOMOTIVE EUROPE', 'HYUNDAI CZECH', 'DUPLICATE',
       'HYUNDAI', 'KIA', 'SSANGYONG', 'ZHAOQING', 'GEELY', 'BYD',
       'GREAT WALL MOTOR', 'NIO', 'ANHUI',
       'MITSUBISHI MOTORS CORPORATION', 'NANJING GOLDEN DRAGON',
       'POLESTAR', 'VOLKSWAGEN', 'AUDI AG', 'OUT OF SCOPE', 'DONKERVOORT',
       'TOYOTA', 'TOYOTA MOTOR CORPORATION', 'BMW AG', 'CHRYSLER',
       'MAZDA', 'LUCID USA', 'SUZUKI MOTOR CORPORATION',
       'FORD MOTOR AUSTRALIA', 'SMART', 'SUBARU', 'FORD MOTOR COMPANY',
       'GENERAL MOTORS HOLDINGS', 'HONDA MOTOR CO', 'MAZDA EUROPE',
       'DALLARA', 'FIAT GROUP', 'MASERATI', 'ALFA ROMEO', 'FERRARI',
       'LAMBORGHINI', 'DR AUTOMOBILES', 'MERCEDES AMG', 'NEXT EGO MOBILE',
       'PORSCHE', 'AUDI SPORT', 'FORD WERKE GMBH', 'MERCEDES-BENZ AG',
       'ALPIN

In [160]:
cars_de['Mh'].isna().sum()

0

In [161]:
cars_de['Man'].unique() 
#can drop this, do not need so much granularity

array(['SKODA AUTO AS', 'TESLA INC', 'SAIC MOTOR CORPORATION LTD',
       'AA-IVA', 'HENAN SUDA ELECTRIC VEHICLE TECHNOLOGY CO LTD',
       'DFSK MOTOR CO LTD', 'JIANGLING MOTOR HOLDING CO LTD',
       'VOLVO CAR CORPORATION', 'LANZHOU ZHIDOU ELECTRIC VEHICLE CO LTD',
       'MITSUBISHI MOTORS THAILAND CO LTD',
       'HYUNDAI ASSAN OTOMOTIV SANAYI VE TICARET AS',
       'BENTLEY MOTORS LTD', 'NISSAN AUTOMOTIVE EUROPE SAS',
       'HYUNDAI MOTOR MANUFACTURING CZECH SRO', 'HYUNDAI MOTOR COMPANY',
       'KIA CORPORATION', 'SSANGYONG MOTOR COMPANY',
       'ZHAOQING XIAOPENG INVESTMENT OF NEW ENERGY CO LTD',
       'ZHEJIANG GEELY AUTOMOBILE CO LTD',
       'BYD AUTO INDUSTRY COMPANY LIMITED',
       'GREAT WALL MOTOR COMPANY LIMITED', 'NIO CO',
       'ANHUI JIANGHUAI AUTOMOBILE GROUP CORP LTD',
       'MITSUBISHI MOTORS CORPORATION',
       'NANJING GOLDEN DRAGON BUS CO LTD', 'POLESTAR PERFORMANCE AB',
       'VOLKSWAGEN AG', 'AUDI AG', 'LADA AUTOMOBILE GMBH',
       'DONKERVOORT AUTOM

In [162]:
cars_de['MMS'].unique() 
#can drop this

array([nan])

In [163]:
cars_de['Tan'].unique() 
#can drop this

array(['e8*2007/46*0349*14', 'e8*2007/46*0349*15', 'e8*2007/46*0349*17',
       ..., 'e6*2007/46*0485*03', 'e6*2007/46*0485*04',
       'e4*2007/46*1399*15'], dtype=object)

In [164]:
cars_de['T'].unique() 
#can drop this

array(['NW', '003', 'AS23P-L', ..., 'T32', 'XU7(EU.M)', 'K14'],
      dtype=object)

In [165]:
cars_de['Va'].unique() 
#can drop this

array(['ABCDLAAX0', 'Y5LD', 'Y6LR', ..., 'AH2S', 'ACDNFEX11', 'ACDTRAX01'],
      dtype=object)

In [166]:
cars_de['Ve'].unique() 
#can drop this

array(['NFD7FD7CW0094BISTNK4C1A0A', 'MFD7FD7CW0094BISTNK3S1A0A',
       'NFM6FM6AJ0214BISTNK3C1A0A', ..., 'HNSP-A1D800', '5GFP-A1D800',
       'FM6SFM6C90124BIVL1C18BCA8M15'], dtype=object)

In [167]:
cars_de['Mk'].unique() 
#can drop this

array(['SKODA', 'TESLA', 'MG. ROEWE', 'AUDI', 'VOLKSWAGEN. VW', nan,
       'SUDA', 'HONDA', 'DFSK. SERES. SOKON', 'DFSK', 'FORD', 'AIWAYS',
       'VOLVO', 'DFSK. SOKON', 'DXK6470AS2F', 'ZHIDOU. ZD. ELARIS',
       'ZHIDOU. ZD', 'MITSUBISHI', 'ISUZU', 'MAHINDRA', 'JEEP', 'SAIC MG',
       'TUERKIYE`NIN OTOMOBILI G.', 'HYUNDAI MOTORSPORT', 'HYUNDAI',
       'BENTLEY', 'NISSAN', 'HONDA MOTOR', 'HYUNDAI MOTOR',
       'HYUNDAI. GENESIS', 'GENESIS', 'KIA', 'SSANGYONG', 'XPENG',
       'SMART', 'LOTUS', 'ZEEKR', 'LYNK&CO', 'MERCEDES-BENZ', 'XINGYUE',
       'LISTERBELL', 'BMW BRILLIANCE (RC)', 'BMW', 'BYD', 'CITROEN',
       'PEUGEOT', 'FAW', 'JETTA', 'GREAT WALL MOTOR COMPANY', 'ORA',
       'GREAT WALL MOTOR COMPANY LIMITED', 'WEY', 'TANK', 'NIO', 'JAC',
       'SKYWELL. SKYWORTH', 'SKYWELL', 'BAIC', 'POLESTAR', 'MAZDA',
       'BRONTO', 'LADA', 'INVEST-AUTO', 'AVTOVAZ', 'WAS', 'DONKERVOORT',
       'UAZ', 'APAL', 'TOYOTA', 'BMW M', 'LUCID MOTORS', 'INFINITI',
       'SUZUKI', 'RIVIAN', 

In [168]:
cars_de['Cn'].unique() 

array(['KAMIQ', 'MODEL Y', 'MG RX6 PLUG-IN HYBRID', ..., 'CIVIC TYPE R',
       'NISSAN MICRA', 'SX4 S-CROSS'], dtype=object)

In [169]:
cars_de['Ct'].unique() 

array(['M1', 'M1G', 'N1G', 'N1', 'N2'], dtype=object)

In [170]:
cars_de['Cr'].unique() 

array(['M1', 'M1G'], dtype=object)

In [171]:
cars_de['r'].unique() 
#can drop this

array([1])

In [172]:
cars_de['m (kg)'].unique() 
#can drop this

array([1262., 1277., 1242., ..., 1862., 1105., 1329.])

In [173]:
cars_de['Mt'].unique() 
#can drop this

array([1398., 1393., 1361., ..., 1049., 1054., 1070.])

In [174]:
cars_de['De'].unique() 
#can drop this

array([nan])

In [175]:
cars_de['Vf'].unique() 
#can drop this

array([nan])

In [176]:
cars_de['Status'].unique() 

array(['P'], dtype=object)

In [177]:
cars_de['Fuel consumption '].unique() 

array([ 5.9,  5.4,  5.5,  5.8,  6.1,  5.7,  5.3,  6. ,  nan,  8. ,  1.8,
        7.2,  6.6,  2. ,  1.9,  0.8,  0.7,  2.5,  2.6,  2.4,  1.1,  1.2,
        1. ,  7.8,  7.6,  5.2,  5.1,  5. ,  6.5,  6.4,  6.3,  5.6,  6.2,
        7.7,  8.4,  4.7,  4.4,  4.5,  4.6,  4.8,  1.4,  6.7,  7.1,  7. ,
        1.6,  4.9,  0.9,  8.3,  7.5,  8.1,  8.2,  8.7,  8.6,  0.6, 11.7,
       11.5,  8.5,  2.2, 11.3, 11.2,  2.1, 11.4,  2.3, 11.1, 10.9, 11.6,
       11. ,  8.8, 10.8,  2.8,  3. ,  2.9,  1.3,  6.8,  1.5,  7.4,  6.9,
        7.9,  7.3,  8.9,  9. , 10.7,  9.2,  9.3,  9.1,  3.8, 10.4, 10.5,
       10.2, 10.3, 10.1, 10. ,  9.9, 10.6,  9.4, 12. , 11.8, 11.9,  3.5,
        4.1, 14. , 14.3,  9.7, 12.1,  3.1, 12.3, 13. , 16.1, 16.4,  9.8,
       13.1, 12.8, 12.9, 12.6, 12.5, 16. , 14.2, 16.9, 12.7,  2.7,  9.6,
       12.2,  3.3,  3.2,  3.4,  3.9,  3.7,  9.5,  4. , 13.3, 13.5, 13.4,
       13.2, 12.4,  1.7, 16.7,  0.5, 13.8, 13.7, 13.6, 13.9, 14.1, 14.9,
       14.8, 15. , 15.1, 15.2, 15.3, 14.7, 20.1, 14

In [178]:
cars_de['Electric range (km)'].unique() 
#this is the column that will help me assess the % of EV

array([ nan,  52., 380., 310., 400., 320., 370., 402., 440., 263., 435.,
       350., 450., 210.,  54., 225., 255.,  48.,  50., 270., 385., 534.,
        62., 484.,  58., 485., 520., 517., 470., 466., 465., 455.,  57.,
       339.,  69., 148., 420., 480., 460., 477., 505., 456., 131., 491.,
        60.,  56.,  53.,  84.,  83.,  78.,  86.,  87.,  81.,  91.,  79.,
        85.,  66.,  71.,  65.,  70.,  68., 799., 200., 237.,  59., 410.,
       441., 426.,  61.,  47.,  46., 408.,  49., 394.,  55., 282., 190.,
        20.,  72.,  75.,  74.,  77.,  64.,  63., 462., 403., 478., 413.,
       482., 469., 472., 396., 476., 407., 414., 434., 405., 437., 436.,
       425., 418., 369., 365., 345., 330.,  42.,  67., 150., 421., 274.,
       267., 404., 273., 265., 417., 272., 100., 106., 105., 101., 104.,
       486., 113., 112., 121.,  73., 471., 454., 442., 495., 808., 771.,
       843., 737., 774., 700., 705., 668., 627.,  76.,  80., 493.,  51.,
        45., 140., 153., 145., 152., 159., 157., 11

In [179]:
cars_de1= cars_de.drop(['VFN', 'Mp', 'Man', 'MMS', 'Tan', 'T', 'Va', 'Ve', 'Mk', 'r', 'm (kg)', 'Mt', 'De', 'Vf'], axis=1)
cars_de1

ID Country         Mh           Cn  Ct  Cr Status  year  \
579410   80049550      DE      SKODA        KAMIQ  M1  M1      P  2022   
579411   80049554      DE      SKODA        KAMIQ  M1  M1      P  2022   
579412   80049559      DE      SKODA        KAMIQ  M1  M1      P  2022   
579413   80049562      DE      SKODA        KAMIQ  M1  M1      P  2022   
579414   80049563      DE      SKODA        KAMIQ  M1  M1      P  2022   
...           ...     ...        ...          ...  ..  ..    ...   ...   
9479257  79719120      DE  DUPLICATE  TOYOTA RAV4  M1  M1      P  2022   
9479258  79898480      DE  DUPLICATE        BAYON  M1  M1      P  2022   
9479259  79898481      DE  DUPLICATE        BAYON  M1  M1      P  2022   
9479260  79978520      DE  DUPLICATE         I 30  M1  M1      P  2022   
9479261  79987802      DE  DUPLICATE  TUCSON IX35  M1  M1      P  2022   

        Date of registration  Fuel consumption   Electric range (km)  
579410            2022-10-17                5.9                  NaN  
579411            2022-05-24                5.9                  NaN  
579412            2022-04-29                5.4                  NaN  
579413            2022-05-11                5.9                  NaN  
579414            2022-05-10                5.4                  NaN  
...                      ...                ...                  ...  
9479257           2022-08-11                NaN                  NaN  
9479258           2022-08-29                NaN                  NaN  
9479259           2022-08-29                NaN                  NaN  
9479260           2022-04-05                NaN                  NaN  
9479261           2022-07-26                NaN                  NaN  

[2570994 rows x 11 columns]

# Meaning of Ct column

M 

Power-driven vehicles having at least four wheels and used for the carriage of passengers.

M1
Vehicles used for the carriage of passengers and comprising not more than eight seats in addition to the driver's seat.
M2 

Vehicles used for the carriage of passengers, comprising more than eight seats in addition to the driver's seat, and having a maximum mass not exceeding 5 tonnes. 

M3 

Vehicles used for the carriage of passengers, comprising more than eight seats in addition to the driver's seat, and having a maximum mass exceeding 5 tonnes. 

N 

Power-driven vehicles having at least four wheels and used for the carriage of goods 

N1 

Vehicles used for the carriage of goods and having a maximum mass not exceeding 3.5 tonnes. 

N2 

Vehicles used for the carriage of goods and having a maximum mass exceeding 3.5 tonnes but not exceeding 12 tonnes. 

In [180]:
#saving both data frames to new csv's

cars_de1.to_csv('cars_de.csv', index=False)

In [181]:
charging_df.to_csv('charging_df.csv', index=False)